// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mindist
double mindist(NumericMatrix train, NumericMatrix test);
RcppExport SEXP CharRecog_mindist(SEXP trainSEXP, SEXP testSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type train(trainSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type test(testSEXP);
    __result = Rcpp::wrap(mindist(train, test));
    return __result;
END_RCPP
}
